CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch \
--nproc_per_node=2 \
--master_port 12358 \
downstream_phase/run_phase_finetuning_ours_timm_GLA_AutoLaparo.py \
--batch_size 32 \
--epochs 30 \
--save_ckpt_freq 5 \
--model vit_base_224_aim_timm \
--pretrained_data wit400m \
--patch_size 16 \
--mixup 0.8 \
--cutmix 1.0 \
--smoothing 0.1 \
--opt adamw \
--lr 3e-4 \
--layer_decay 0.1 \
--weight_decay 5e-2 \
--warmup_epochs 3 \
--data_path /project/mmendoscope/surgical_video/AutoLaparo \
--eval_data_path /project/mmendoscope/surgical_video/AutoLaparo \
--nb_classes 7 \
--data_strategy online \
--output_mode key_frame \
--num_frames 8 \
--sampling_rate 4 \
--data_set AutoLaparo \
--train_data_fps 1fps \
--test_data_fps 1fps \
--output_dir /home/syangcw/SurgPETL/AutoLaparo/PETL/LGA/ \
--log_dir /home/syangcw/SurgPETL/AutoLaparo/PETL/LGA/ \
--num_workers 32 \
--dist_eval \
--no_auto_resume